addSbtPlugin("com.eed3si9n"        % "sbt-buildinfo"     % "0.9.0")
addSbtPlugin("org.scoverage"       % "sbt-scoverage"     % "1.6.1")
addSbtPlugin("org.scalameta"       % "sbt-mdoc"          % "2.1.5")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"      % "2.3.4")
addSbtPlugin("com.geirsson"        % "sbt-ci-release"    % "1.5.3")
addSbtPlugin("de.heikoseeberger"   % "sbt-header"        % "5.6.0")
addSbtPlugin("com.alejandrohdezma" % "sbt-github-header" % "0.8.1")
addSbtPlugin("com.alejandrohdezma" % "sbt-mdoc-toc"      % "0.2")
